### ISSUE TITLE
希望加入验证码归拢功能

### ISSUE THREAD

**Issue by xseven007** [tianma8023/XposedSmsCode#10]
希望加入验证码归拢功能，类似一加手机或者其他国内手机系统那样

**Comment by tianma8023** [comment]
@xseven007 
我这个模块并没有 Hook 系统短信，事实上也不可能 Hook 系统默认短信App，因为任何可以作为短信 App 的应用（比如各家Rom自带的系统短信，Google Message 等等）都可以被设置成为默认短信App，不可能同时 Hook 这么多短信 App 的。

另外你说的，验证码归拢功能，其实我的模块本身已经有了保存 “验证码历史记录” 的功能，实际上已经做了类似归拢的功能，你可以试试看。推荐的功能组合是 "验证码短信拦截" + "显示通知" + "自动清除通知" + "启用验证码记录"

**Comment by xseven007** [comment]
@tianma8023 我现在用的差不多就算这样设置的，因为之前另一台手机上安装有阿里小号这个APP，这个APP有android.permission.WRITE_SMS 权限，可以把小号转发来的验证码归拢到一起。所以我认为加入这个功能会更好一些

**Comment by tianma8023** [comment]
@xseven007 
不太明白阿里小号是做什么的，也不清楚自己该做什么。

**Comment by xseven007** [comment]
@tianma8023 阿里小号有点类似于“和多号”一样的一卡多号效果，然后它会把发到小号的短信全部归拢在一起，在系统自带的短信app里就可以看到，是通过建一个联系人的方式。比如我小号是156xxxxxxxx，把这个号码在通讯录里命名为工作号，那么如果一个188xxxxxxxx的号码发短信到156xxxxxxxx的话，阿里小号这个app就会把这些短信全部归类到工作号这个联系人发来的短信了，并在短信末尾加上来自188xxxxxxxx。这样的效果

**Comment by tianma8023** [comment]
@xseven007 
你描述的我大概了解了，具体内在的逻辑是怎么运作的其实我不太清楚。所以，我下载了 “阿里小号”，但是发现已经不让注册开通小号了，而我的卡又是联通的，用不了 “和多号”。

所以暂时没办法去研究你说的这个功能。

**Comment by xseven007** [comment]
@tianma8023 有一个不懂是否正确的思路。XposedSmsCode可以获取到短信内容，然后是不是也可以通过短信写入权限，把获取到的内容写到另一个号码发来的消息记录中呢？如果可以这样的话，那么是不是可以考虑在通讯录生成一个虚假的电话号码联系人，专门用来写入获取到的验证码短信内容。
