### ISSUE TITLE
最新版android 10中不工作

### ISSUE THREAD

**Issue by Greyh4t** [tianma8023/XposedSmsCode#11]
最新版的android 10中，InboundSmsHandler类里的dispatchIntent方法最后多了一个参数，导致hook短信失败，具体代码可以在这里看到
https://android.googlesource.com/platform/frameworks/opt/telephony/+/refs/heads/master/src/java/com/android/internal/telephony/InboundSmsHandler.java#1128

然后xposed里启动的时候会报错，导致直接获取不到短信验证码了

**Comment by tianma8023** [comment]
fixed
