### ISSUE TITLE
Issue: EdExposed Sandhook

### ISSUE THREAD

**Issue by ram108** [tianma8023/XposedSmsCode#12]
Does not work with EdExposed Sandhook.
![Screenshot_20200112-001735](https://user-images.githubusercontent.com/2060570/72210755-61181980-34d1-11ea-8233-769e6edf2d74.png)
![Screenshot_20200112-001805](https://user-images.githubusercontent.com/2060570/72210756-61b0b000-34d1-11ea-8f13-f91d1d984eb7.png)
![Screenshot_20200112-001759](https://user-images.githubusercontent.com/2060570/72210757-61b0b000-34d1-11ea-8d86-6c67abf93f5e.png)

**Comment by ram108** [comment]
It is a problem with EdExposed Sandhook v0.4.6.
Installed v0.4.5.1 and everything is OK.

**Comment by tianma8023** [comment]
@ram108 What's the version of your magisk? And please show me the EdXposed log after device reboot.
