### ISSUE TITLE
中国银行APP 付款时验证码的问题

### ISSUE THREAD

**Issue by kidzgy** [tianma8023/XposedSmsCode#15]
先说明一下，中国银行APP付款时输入验证码，是输完6个数字直接跳转成功的，不像建行的需要按确定按钮。
那么问题来了，我在模块里设置自动输入验证码，中国银行APP是会自动输入6个数字，但是不会跳转，然后我想编辑删除掉数字自己手动输入，发现已经输入的验证码还删除不掉。
故我自己先把中国银行APP排除了，手动输入。

**Comment by kidzgy** [comment]
哦再有一个问题就是，建设银行APP付款时，并不会自动输入验证码。

**Comment by kidzgy** [comment]
环境是，小米10pro，安卓10.

**Comment by tianma8023** [comment]
@kidzgy 关于你的第一个问题，为了专门解决中国银行App自动输入之后无法登录的问题，所以模块已经加了自动输入屏蔽设置。你设置一下屏蔽就行。至于为啥无法自动登录，这是中国银行App自己的问题。

**Comment by tianma8023** [comment]
@kidzgy 关于第二个问题，刚刚下载了建行App看了下，因为我没有建行卡，没办法到你说的付款页面，走了下注册流程，发现建行App用的App自己的键盘，这个可能是没办法自动输入验证码的原因。因为如果建行App自定义的键盘没有完全按照规范来实现的话，那很可能就没办法自动输入。

所以这个问题，目前应该是没办法解决。
