### ISSUE TITLE
请问EdXposed开启白名单模式后需要启用哪些应用才能正常输入验证码？

### ISSUE THREAD

**Issue by ChenilleJoes** [tianma8023/XposedSmsCode#16]
![IMG_20200512_065453](https://user-images.githubusercontent.com/55339634/81620099-a61b7080-941d-11ea-9f42-523106af5ff5.jpg)

请问EdXposed开启白名单模式后需要启用哪些应用才能正常输入验证码？我手机是miui12安卓10。需要把短信/电话和短信储存都加进去吗？

**Comment by tianma8023** [comment]
@ChenilleJoes 模块右上角菜单栏，有一个 “太极用户须知” 里面有说需要加入的应用，就是EdXposed白名单需要加入的应用。简单理解就是EdXposed白名单模式跟太极阳差不多。
需要加入两个：电话服务(com.android.phone) 和 Android系统(android)

**Comment by ChenilleJoes** [comment]
ok👌

> @ChenilleJoes模块右上角菜单栏，有一个“太极用户须知”里面有说需要加入的应用，就是EdXposed白名单需要加入的应用。简单理解就是EdXposed白名单模式跟太极阳差不多。
> 需要加入两个：电话服务（com.android.phone）和Android系统（android）

ok👌
