### ISSUE TITLE
验证码提取错误

### ISSUE THREAD

**Issue by Greyh4t** [tianma8023/XposedSmsCode#17]
【恒生芸泰】北京协和医院APP提醒您已预约(东院)国际医疗部2020-08-20 08:00:00 第5号。入院当日患者及家属需填写协和通行证https://inquiry.iflyhealth.com/wx#/official/T309?deptcode=a3&device=qr&custom=1 ，并在入院时出示（当日有效）.请您就诊前15分钟进入院区候诊，持就诊卡在自助机报到或使用APP门诊报到功能报到。每位患者间隔15分钟。初次就诊患者需持有效证件原件在自助机或综合服务窗口建档审核。商保患者请在就诊当天到综合服务窗口办理手续。国际医疗部门诊位于内科楼南端，邻近院区南门。车辆从南门进入院区。工作日工作时间优先从一层进入诊区，也可从二层进入。夜间门诊和周末门诊时间从一层入口进入诊区。疫情期间请您仔细阅读APP上“来院患者提示”。客服电话400-893-3900。短信不作为就诊凭证。

上面这条短信不包含验证码，但是会将T309识别为验证码，能否优化下策略或者加个白名单功能？

**Comment by tianma8023** [comment]
@Greyh4t 不好意思，一直没看到这个 issue，因为验证码关键字默认是有 “Code” 的。这里的链接带了 code 会被认为是验证码短信。所以如果不需要的话，可以把这个关键字去掉，应该就ok了

**Comment by Greyh4t** [comment]
> 

好的，谢谢，不过我现在都不用android机了😄
