### ISSUE TITLE
Gboard 输入法在一些应用中不能自动输入验证码

### ISSUE THREAD

**Issue by eallion** [tianma8023/XposedSmsCode#18]
### Gboard 输入法在一些应用中不能自动输入验证码

大概原因是不能切换到数字输入状态。（虽然一些应用不遵守开发规范

**Comment by tianma8023** [comment]
@eallion 抱歉，现在想起来回复，，这个问题暂时无解，因为自动输入验证码的逻辑本身不涉及到输入法，因而没办法对输入法做兼容&适配。目前确实在部分App内（不知道这些App里面做了什么神奇操作:( ）,输入法没办法自动输入...

**Comment by eallion** [comment]
好的
