### ISSUE TITLE
Doesn't work with Disa

### ISSUE THREAD

**Issue by drkui** [tianma8023/XposedSmsCode#2]
I use an app called Disa to get SMS and the module isn't copying the codes when I get them on the app.

**Comment by drkui** [comment]
@tianma8023 
After testing again, it does look like it's working properly. I'm not sure what the problem was before, maybe it was just a fluke or something. 

If I have any more problems in the future, I'll be sure to post my Xposed log for you to take a look.

**Comment by tianma8023** [comment]
@drkui 
Now you can update to the latest release(v1.3.0) from Xposed Repo or this repo. It may fix the bug you encountered. XD

**Comment by tianma8023** [comment]
@drkui hi drkui.
If u don't have any other questions, please close this issues.
