### ISSUE TITLE
[Suggestion] Pre-installed keywords for RU locale

### ISSUE THREAD

**Issue by VladWinner** [tianma8023/XposedSmsCode#22]
Hello! XposedSmsCode has a good number of preset settings, but it would be great if you included also these keywords in the selection for users with RU-localized (Russian) Android:
`|Код|код|КОД|Пароль|пароль|ПАРОЛЬ|Промокод|промокод|ПРОМОКОД|Никому не|никому не|НИКОМУ НЕ|Для|для|ДЛЯ|Введите|введите|ВВЕДИТЕ|Kod|kod|KOD|Nikomu|nikomu|NIKOMU`

This collection was collected after analyzing more than 700 service messages with one-time codes. After two days of testing, I found that the app now successfully copies the code from all such messages, which is very great for our country, where SMS messages with exactly such words always contain codes.

Yes, I know that anyone can set custom options for keywords, but it would still be convenient to make such presets for the convenience of other users who do not know what exactly to enter to keywords field for normal use.

Thanks for your hard work!

**Comment by tuyennn** [comment]
See https://github.com/tianma8023/XposedSmsCode/pull/49, this could be closed
