### ISSUE TITLE
你好 源码好像不全？无法编译

### ISSUE THREAD

**Issue by azurefang** [tianma8023/XposedSmsCode#23]
import com.github.tianma8023.xposed.smscode.BuildConfig;
import com.tianma.xsmscode.data.db.entity.AppInfoDao;
import com.tianma.xsmscode.data.db.entity.SmsCodeRuleDao;
import com.tianma.xsmscode.data.db.entity.SmsMsgDao;
import com.tianma.xsmscode.data.db.entity.DaoMaster;
import com.tianma.xsmscode.data.db.entity.DaoSession;
import com.tianma.xsmscode.data.db.entity.SmsCodeRuleDao;

这些找不到

**Comment by tianma8023** [comment]
@azurefang BuildConfig, XxxDao 这些类是构建(build)过程生成的。如果你使用的 ide 是 Android Studio 的话，可以重新 build 一下，应该就能生成了。

**Comment by azurefang** [comment]
好的 第一次搞不太懂 现在可以了
