### ISSUE TITLE
LSPosed

### ISSUE THREAD

**Issue by aaref1234** [tianma8023/XposedSmsCode#24]
The module was working on LSPosed v1.1.0 and now it is not working on LSPosed v1.2.2 

What applications must be enabled for the module to work .

**Comment by tianma8023** [comment]
@aaref1234 You can refer to "EdXposed Users Notice" cause LSPosed is based on (forked from) EdXposed.
You may add these apps:
- Phone Services(com.android.phone)
- Android System(android)

**Comment by aaref1234** [comment]
Thank you .
