### ISSUE TITLE
不支持安卓S

### ISSUE THREAD

**Issue by Rakau** [tianma8023/XposedSmsCode#26]
RT，模块作用域已经勾选系统框架和电话服务了

**Comment by tomatolei** [comment]
安卓12测试没用，等待更新

**Comment by tianma8023** [comment]
@Rakau @tomatolei 已知问题，Android 12 相关系统 API 变更巨大，等我升上 12 后适配

**Comment by Rakau** [comment]
谢谢开发者

Tianma ***@***.***> 于 2022年1月12日周三 11:30写道：

**Comment by tianma8023** [comment]
@Rakau @tomatolei 已适配，欢迎体验
