### ISSUE TITLE
Code is detected on A12, but is not copied to clipboard automatically

### ISSUE THREAD

**Issue by Kellwaxx11** [tianma8023/XposedSmsCode#28]
Hi, I installed the module on A12 with LSPosed 
enables for Android system and Phone Services

the toast notification showing the correct code being detected, but clipboard copy and autofill not working

**Comment by likun880615** [comment]
老乡我的安卓12不能自动填验证码
[https://likun666.lanzouo.com/iuw9pzj3ktg]()

**Comment by tianma8023** [comment]
@Kellwaxx11  Try the latest app plz. V2.2.6 fixed these issues.
