### ISSUE TITLE
安卓12失效了

### ISSUE THREAD

**Issue by likun880615** [tianma8023/XposedSmsCode#29]
这是我的lsposed日志蛮烦老哥看一下
https://likun666.lanzouo.com/iuw9pzj3ktg

**Comment by tianma8023** [comment]
@likun880615 已修复，请用最新版

**Comment by likun880615** [comment]
好的谢谢了!



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月24日(周四) 凌晨0:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tianma8023/XposedSmsCode] 安卓12失效了 (Issue #29)




 
@likun880615 已修复，请用最新版
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
