### ISSUE TITLE
建议：应用黑名单

### ISSUE THREAD

**Issue by eallion** [tianma8023/XposedSmsCode#31]
建议屏蔽一些应用自动填入验证码。

比如在用`中国银行 APP`转账时，自动填入验证码的话，页面不能提交，有可能是因为该应用内置了安全键盘所致。每次转账都要禁用这个插件。

**Comment by tianma8023** [comment]
已经有此功能了。 “自动输入屏蔽设置” 可以选择哪些App里面不需要自动输入

**Comment by tianma8023** [comment]
@eallion  用新版本的模块试试看，可能你用的是旧版的

**Comment by eallion** [comment]
嗯，好的，谢谢。
