### ISSUE TITLE
[suggestion]Join LSPosed Module Repository

### ISSUE THREAD

**Issue by zhongfly** [tianma8023/XposedSmsCode#33]
You can submit modules to LSPosed module repository, and this modules can be downloaded in LSPosed.
https://github.com/Xposed-Modules-Repo/submission

**Comment by zhongfly** [comment]
And why not update readme.md:

> Support Xposed, EdXposed and TaiChi·Magisk

to

> Support Xposed, EdXposed, LSPosed and TaiChi·Magisk

**Comment by tianma8023** [comment]
@zhongfly Thanks for your suggestion. I have already submitted this module to LSPosed repo. And I'll update the readme later.
