### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by 3166265725** [tianma8023/XposedSmsCode#35]
系统：evolution x，Android12L
具体描述：不能拦截短信通知，且关闭助手内的显示通知选项后，仍会有电话服务发送验证码通知，且不会自动清除通知。就是说现在来验证码会给我发两条通知（短信和电话服务）。

**Comment by Rakau** [comment]
+1

**Comment by tianma8023** [comment]
@3166265725 @Rakau 可能是宿主App没有读取到XposedSmsCode的开关配置，导致会有各种异常出现，后续我研究下如何处理

**Comment by tianma8023** [comment]
@3166265725 @Rakau 最新版 2.3.0 已解决此问题，欢迎体验

**Comment by Rakau** [comment]
经测试确认已修复
