### ISSUE TITLE
目前是否支持读取英文验证码?

### ISSUE THREAD

**Issue by jiang-yuan** [tianma8023/XposedSmsCode#36]
人在国外,  用的ColorOS12系统自带功能只能读取中文验证码
目前是否支持读取英文短信验证码?

**Comment by tianma8023** [comment]
@jiang-yuan 支持的，但是可能需要自定义验证码规则，目前通用的识别关键字就是 Code 之类的，你可能需要按需加入 Verification Code 之类的关键词

**Comment by jiang-yuan** [comment]
已经添加OTP关键字我在新加坡,基本上收到的都是都是OTP,建议加入默认配置
&nbsp;


Yuan&nbsp;Jiang(江原)
***@***.***



&nbsp;




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2022年5月16日(星期一) 下午5:38
To: ***@***.***&gt;; 
Cc: "Yuan ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [tianma8023/XposedSmsCode] 目前是否支持读取英文验证码? (Issue #36)





 
@jiang-yuan 支持的，但是可能需要自定义验证码规则，目前通用的识别关键字就是 Code 之类的，你可能需要按需加入 Verification Code 之类的关键词
