### ISSUE TITLE
桌面状态开启自动输入会跳转爱奇艺

### ISSUE THREAD

**Issue by zsylife** [tianma8023/XposedSmsCode#37]
只有在桌面 开启自动输入验证码的情况
会出现自动启动爱奇艺
https://user-images.githubusercontent.com/41839622/165304814-be19cf48-c513-48e1-ab72-434e673a24e6.mp4

**Comment by tianma8023** [comment]
我看你发的视频用的是一加系统，是不是此系统的系统桌面有类似于全局搜索的功能（比如 miui 系统就有一款名为 "搜索" 的系统App，用于全局搜索），这种App会在桌面上占用输入焦点。因为XposedSmsCode自动输入的时候就是在当前输入焦点直接自动输入的，所以就会出现视频中的现象。

这个问题对本模块来说，是解决不了的，因为本模块的作用域只有 (电话服务 和 Android系统)，没办法通过 Hook 其他特定的App来降低误输入的可能性。

未来有可能的话，可以考虑加入自定义的自动输入延迟，这样大家会有一定的反应时间，不至于特别仓促。

**Comment by tianma8023** [comment]
@zsylife 我刚刚用小米手机测试了下，安装了爱奇艺之后，自动输入任何文本，爱奇艺都会自动打开，所以可能是爱奇艺做了什么黑科技的事情监听了系统并响应了输入。

目前有下面几种解决方案：
- 模块有自动输入屏蔽的功能，将桌面App添加到屏蔽列表里面。这样就不会在桌面App里自动输入验证码了
- 把爱奇艺关进小黑屋，需要时再enable它
- 自定义自动输入的延迟

**Comment by zsylife** [comment]
> 

自定义自动输入的延迟已经实装了吗？2.2.7版本没看到相关选项

**Comment by tianma8023** [comment]
@zsylife 使用最新的 2.3.0 已经有了延迟输入功能，欢迎体验
