### ISSUE TITLE
大约2个月前开始验证码会弹2次通知以及自动输入2次

### ISSUE THREAD

**Issue by lupohan44** [tianma8023/XposedSmsCode#43]
设备 Pixel 5
系统 安卓12
当前短信app版本 版本 messages.android_20220621_01_RC00.phone.openbeta_dynamic (不知道是否有关)

**Comment by tianma8023** [comment]
@lupohan44 尝试卸载重装最新版的模块App试试看，记得重启

**Comment by lupohan44** [comment]
照着做完后问题消失
