### ISSUE TITLE
功能建议 监听通知提取验证码

### ISSUE THREAD

**Issue by lupohan44** [tianma8023/XposedSmsCode#44]
建议新增一个功能, 通过申请通知访问权限, 监听通知提取验证码
例如:
监听验证码转发APP, 就可以提取其他手机收到的验证码
监听邮箱APP, 就可以提取邮箱验证码

监听的APP可以做一个选单勾选

**Comment by tianma8023** [comment]
@lupohan44 这个想法很好，但实际上操作起来很难。

因为 Android 系统本身也没有对App的通知内容进行约束，啥内容都能出现。举个例子，QQ邮箱App的通知内容是邮件的标题，那比如百度或者steam发的邮箱验证码之类的邮件，这些邮件标题本身是没有带验证码的，根本识别不了。

那实际操作下来就是会可能有部分通知里面的内容能解析出来验证码，但更大部分是根本解析不出来(因为通知里面根本没有)，实际上就会让用户觉得识别率低，无堪大用。实际上做了也是吃力不讨好。

**Comment by lupohan44** [comment]
> @lupohan44 这个想法很好，但实际上操作起来很难。
> 
> 因为 Android 系统本身也没有对App的通知内容进行约束，啥内容都能出现。举个例子，QQ邮箱App的通知内容是邮件的标题，那比如百度或者steam发的邮箱验证码之类的邮件，这些邮件标题本身是没有带验证码的，根本识别不了。
> 
> 那实际操作下来就是会可能有部分通知里面的内容能解析出来验证码，但更大部分是根本解析不出来(因为通知里面根本没有)，实际上就会让用户觉得识别率低，无堪大用。实际上做了也是吃力不讨好。

我刚测试了一下, gmail的通知内容是标题+内容, 网易邮箱大师不知道什么原因似乎不弹出通知, 我用Telegram转发验证码, telegram的通知也是完整的消息, 应该识别率不会低的

**Comment by Gokou-Ruri** [comment]
我用的k9，通知里是能看到验证码的。

**Comment by TestSmirk** [comment]
国内通知不给返回短信内容的，特别华为之类，锁屏的时候。
这个功能不属于xposed的范畴。普通app也可以做，没必要。

**Comment by lupohan44** [comment]
> 国内通知不给返回短信内容的，特别华为之类，锁屏的时候。 这个功能不属于xposed的范畴。普通app也可以做，没必要。

这里指的不是短信的通知 指其他APP来的通知 比如邮箱APP 短信转发APP之类的

**Comment by lupohan44** [comment]
好像在app里面没看到这个功能 是不会去实现了吗？
