### ISSUE TITLE
Android13 无法自动填写验证码

### ISSUE THREAD

**Issue by kuind** [tianma8023/XposedSmsCode#46]
如题

[LSPosed_2022-09-12T17_23_10.962264.zip](https://github.com/tianma8023/XposedSmsCode/files/9546693/LSPosed_2022-09-12T17_23_10.962264.zip)

**Comment by tianma8023** [comment]
@kuind 我手头目前没有 Android 13 设备，你这边方便帮忙一起测试吗？

**Comment by tianma8023** [comment]
@kuind Hi, 可以用[2.4.0 版本](https://github.com/tianma8023/XposedSmsCode/releases/tag/2.4.0)，适配了 Android 13，你可以看看还有没有什么问题
