### ISSUE TITLE
可否加入对“无忧行”app的短信验证码识别+提取

### ISSUE THREAD

**Issue by zyh941** [tianma8023/XposedSmsCode#48]
当前在用模块2.4.0版，手机是Pixel 5，运行原生Android 13，常规的系统短信能正常提取复制，不过我平时比较常用到无忧行号码托管功能，所有短信都通过app来下发（格式跟常规短信完全一样）。我已经尝试过勾选system framework和无忧行app，发现来信时不能提取验证码，请问能不能加上对它的支持呢？又或者是我的操作方式不对？

**Comment by tianma8023** [comment]
@zyh941 Hello

这个”无忧行“app，我大概看了下，这个app会把发送到托管卡的短信以无忧行app的通知的形式转发给用户。实际上这个流程，跟接收短信没关系，因为根本就没走你当前手机的短信系统。所以肯定是无论怎么勾选都不起作用。

要实现你这个效果，实际上要开发专门的插件针对”无忧行“app，这就是另一款插件的事情了，不属于本插件目前的业务范畴
