### ISSUE TITLE
1.7

### ISSUE THREAD

**Issue by Rakastanyan** [tianma8023/XposedSmsCode#5]
在我的MIUI欧盟版不能使用，但是1.6能使用

**Comment by tianma8023** [comment]
@Rakastanyan 请提供一下手机型号，rom版本，Android 版本，Xposed版本 等等相关信息。

**Comment by Rakastanyan** [comment]
米mix2，MIUI10.3 by xiaomi.eu9.1.17开发版，安卓8.0，xposed 90-beta2

**Comment by tianma8023** [comment]
@Rakastanyan  能提供一下 Xposed 日志吗？（先接收一条验证码短信之后，把 Xposed 日志从 Xposed Manager 中导出）

按理来讲，1.6.0 升级到 1.7.0 是不会出问题的。你可以重新勾选，并重启系统试试看。

另外你可以看一下 App 内部的 “常见问题” 中的 “模块失效怎么办？” 这一问题。

**Comment by tianma8023** [comment]
@Rakastanyan 最新版 [XposedSmsCode 2.0.0](https://github.com/tianma8023/XposedSmsCode/releases/tag/2.0.0) 已发布，无后台，请尝试新版本。
