### ISSUE TITLE
缺少 com.github.tianma8023.xposed.smscode.R 无法编译呃

### ISSUE THREAD

**Issue by shiqwang** [tianma8023/XposedSmsCode#50]
缺少 com.github.tianma8023.xposed.smscode.R 无法编译呃

**Comment by tianma8023** [comment]
@shiqwang ${packageName}.R 是 Android 项目构建过程中用于引用资源的类，这个类会在 Android 工程编译的过程的中间产物，所以你这边 `Sync Project with Gradle Files` 或者 build 一下工程，应该就不会报错了

**Comment by shiqwang** [comment]
哦哦哦 好的 我这边已经成功啦 多谢
