### ISSUE TITLE
redmi k40无法使用验证码短信标记为已读

### ISSUE THREAD

**Issue by wordscode** [tianma8023/XposedSmsCode#51]
完我使用的是miui13系统自带的短信app，但是这也不能使用标记短信为已读功能，有什么办法排除，解决问题吗？

**Comment by tianma8023** [comment]
@wordscode 试验性功能，本身就不稳定。标记为已读大部分系统都不生效，高版本Android系统生效的几率更渺茫。没有通用的方案解决这个问题。
