### ISSUE TITLE
请问一下，如何获取接收到短信的手机号呢？

### ISSUE THREAD

**Issue by shiqwang** [tianma8023/XposedSmsCode#52]
请问一下，如何获取接收到短信的手机号呢？我可能需要维护多台手机，但是如果都发到数据库里面的话 就不知道是哪个手机卡收到的信息了

**Comment by tianma8023** [comment]
@shiqwang  参考这个模块：[SIMNumberSetter](https://github.com/KieronQuinn/SIMNumberSetter)
