### ISSUE TITLE
Unable to hide launcher icon on Pixel Launcher

### ISSUE THREAD

**Issue by tuyennn** [tianma8023/XposedSmsCode#53]
- Pixel Launcher
- Android 13
- Enable module with `hide launcher icon` enabled.
- Launcher icon was still persist

**Comment by tianma8023** [comment]
@tuyennn For Pixel Launcher user, you may long press the app's launcher icon -> customize -> hide shortcut.

**Comment by tuyennn** [comment]
@tianma8023 thanks for the great module, well your guide seem doesn't exist. I temporary had to use com.metris.xposed.pmods for workaround
