### ISSUE TITLE
有时候验证码会输入两遍

### ISSUE THREAD

**Issue by 610364023** [tianma8023/XposedSmsCode#55]
大概10次里出现3次

**Comment by 610364023** [comment]
![IMG_20230502_181806](https://user-images.githubusercontent.com/45279039/235641068-87609d5a-06b5-48cd-be7a-a26a6a5e6a3b.jpg)
验证码记录里全部双份的

**Comment by tianma8023** [comment]
@610364023  这种情况，建议你卸载模块 -> 重启手机 -> 重装模块 -> 重启手机。或者把 短时间内过滤重复短信 开关打开
