### ISSUE TITLE
大佬，方便请教下怎么获取到短信的内容吗

### ISSUE THREAD

**Issue by KOFKOY** [tianma8023/XposedSmsCode#56]
我看代码里作用域是这两个   <item>android</item>   <item>com.android.phone</item> ，这是hook的手机操作系统吗，可以hook短信app里面接受短信广播的方法吗
我看有很多正常的app能读取到短信内容，它们都是怎么实现的呢

**Comment by KOFKOY** [comment]
![image](https://github.com/tianma8023/XposedSmsCode/assets/30439085/c2f0df88-18d4-40a1-b578-fdeb229c269d)
我想hook f.g.b.s.e.f$a 的 onReceive方法，获取Intent，一直没反应，不知道是因为权限问题，还是思路错了

**Comment by tianma8023** [comment]
有几个思路：
1. 这个 apk 有没有hook成功，比如你可以hook一下主界面或者这个app的application, 看看能不能成功hook
2. 这个包里面还有没有其他的 BroadcastReceiver 能处理 android.provider.Telephony.SMS_RECEIVED 这个广播

更多的，可能要看下你的代码以及这个apk包了

**Comment by KOFKOY** [comment]
放弃了，搞不定
