### ISSUE TITLE
Support Android 14

### ISSUE THREAD

**Issue by tuyennn** [tianma8023/XposedSmsCode#57]
As title, doesn't seem it works.

**Comment by Aryeh95** [comment]
Same issue with the Pixel 8 Pro on Android 14

**Comment by RainHoutas** [comment]
same in pixel5

**Comment by tianma8023** [comment]
I need Xposed(Lsposed) log for more detailed information.

You may follow these steps:
1. Switch on the 'Detailed Log' in XposedSmsCode app. 
2. Reboot your device
3. Receive a SMS message which contains verification code.
4. Export the LSPosed log to local device and send these log files to me

**Comment by Aryeh95** [comment]
I captured a log.
SMS arrived at 10:58pm local time
https://drive.google.com/file/d/17ktTMQP7l8DcTkNUcGazjG6YuJIF46u8/view?usp=drivesdk

**Comment by tianma8023** [comment]
@tuyennn @Aryeh95 done. You can upgrade to the latest plz.

**Comment by Aryeh95** [comment]
Upgraded and confirmed working. Thank you!
