### ISSUE TITLE
無法正確識別

### ISSUE THREAD

**Issue by newererw** [tianma8023/XposedSmsCode#6]
感謝您使用信用卡，卡號後四碼1234於今日網路交易約TWD 4567元，交易密碼為7890，請於5分鐘內輸入完成認證。

應為7890,但卻辨識為1234
正則表示已經列入交易密碼，但似乎不是辨認最近距離的7890，依舊是1234
煩請協助

**Comment by tianma8023** [comment]
@newererw 这种格式的短信内容确实比较特殊，需要我改善一下处理算法。

**Comment by tianma8023** [comment]
已修复 [XposedSmsCode 2.0.0](https://github.com/tianma8023/XposedSmsCode/releases/tag/2.0.0)

**Comment by newererw** [comment]
謝謝更新，很棒的工具

**Comment by tianma8023** [comment]
@newererw 不用谢~ 都是应该的~
