### ISSUE TITLE
錯誤輸入法時，數字會以輸入法輸出

### ISSUE THREAD

**Issue by newererw** [tianma8023/XposedSmsCode#8]
提出一個小問題
錯誤輸入法時，數字會以輸入法輸出，
例如數字為2589，但鍵盤輸入法不是數字鍵盤，
我是注音輸入，就會輸出在2589的注音符號，
感謝你快速回應，我用過google的gboard注音輸入，
或單獨安裝的搜狗注音都如此，
但用剪貼簿貼上是正確的數字，
是否可以預設輸出時切換為英數鍵盤？
或以貼上方式而非鍵盤按鍵輸出？
感謝您的協助

**Comment by tianma8023** [comment]
@newererw 请问你使用的是什么输入法？？能提供相关截图信息吗？

**Comment by newererw** [comment]
2589在注音鍵盤會像這樣輸出
![Screenshot_2019-07-17-00-44-22-768_com android chrome](https://user-images.githubusercontent.com/48615730/61313137-6cdd9880-a82c-11e9-8044-1a79b0612dbd.jpg)

**Comment by tianma8023** [comment]
@newererw 原来如此，我大致了解你这边的问题了。因为之前从没用过注音的输入法，所以不太了解。我会去研究研究能不能解决这个问题。有好消息就在这里通知你。

**Comment by tianma8023** [comment]
@newererw 
Hi. 我这边研究到现在，没发现有很好的方案去解决现在这个问题。没能找到侵入性小的解决方案，实在是抱歉。
再就是，因为一般的验证码输入框，都是只允许输入数字的，输入法此时会自动切到数字键盘。所以，我猜你这边碰到这种例外情况应该也是比较少的。暂时没有好的解决方案的话，你这边只能注意一下在例外情况下提前切换至数字键盘。

**Comment by tianma8023** [comment]
@newererw 我这边应该是已经有解决方案了，方便留一个联系方式吗？我想跟你聊一下关于这个问题的处理，再就是希望你能帮忙测试一下。

**Comment by newererw** [comment]
確實這狀況很少見，很開心能協助測試，我的email是newer39@gmail.com，感謝你

**Comment by tianma8023** [comment]
@newererw 
Hi，目前的最新版（2.2.0），加入了自动输入应用屏蔽功能。就跟我们之前讨论过的一样，由于这种在验证码输入框中的键盘类型不是数字键盘的情况应该比较少，所以你可以直接将这些有问题的App加入自动输入的黑名单，这样就不会注音输入了。
