### ISSUE TITLE
关于 build.gradle 中keystore 的一些疑惑？

### ISSUE THREAD

**Issue by einverne** [tianma8023/XposedSmsCode#9]
在拉取代码导入 IDE 之后发现 `build.gradle` 中硬编码了 keystore 路径，发现我本地可能无法 build，对于这个问题是不是可以在代码中使用一个 debug 的 key 来进行开发，在发布时再使用私有的 key 发布？

**Comment by tianma8023** [comment]
@einverne 这是个问题，我修复一下。

**Comment by tianma8023** [comment]
@einverne Hi，实在不好意思。
我的本意是，没有 keystore 等文件的话，在build过程中就不进行签名的，但是没注意到签名相关的 property 文件缺失会报错。作为原作者，肯定是不能把 keystore 相关文件也放上来的。

你想的那种解决方案也行，自己可以另外搞一套签名，只不过签名不一样话，没办法覆盖安装罢了。

**Comment by tianma8023** [comment]
@einverne 最新的 [commit a03954c](https://github.com/tianma8023/XposedSmsCode/commit/a03954c356c4318ca2b35bfe787902ab5df98511) 修复了这个问题。

**Comment by einverne** [comment]
另外一个问题，Windows 的路径在 Linux 下面是非法字符。
